export const translations = {
  es: {
    title: "Alan Hiram | Portfolio",
    name: "Alan Hiram Álvarez Bazán",
    role: "Developer",
    nav_about: "Sobre mí",
    nav_skills: "Competencias",
    nav_contact: "Contacto",
    hero_label: "CV",
    hero_subtitle: "6° semestre ISC · ITM — Project Manager IEEE CS",
    about_title: "Sobre mí",
    about_bio: "Estudiante de ISC apasionado por el desarrollo de software, la automatización y la inteligencia artificial. Como Project Manager en IEEE CS, lidero equipos técnicos y gestiono proyectos innovadores. Además, soy miembro activo de la Selección de Ajedrez del ITM, lo que fortalece mi pensamiento lógico y análisis estratégico.",
    skills_title: "Competencias",
    skill_leadership: "Liderazgo",
    skill_leadership_desc: "Gestión de equipos técnicos, trabajo en equipo y buena comunicación. Coordinación de proyectos como PM en IEEE CS.",
    skill_software: "Desarrollo de Software",
    skill_software_desc: "Arquitectura y desarrollo de aplicaciones web y de escritorio, integrando entornos virtualizados y laboratorios en Linux mediante contenedores Docker.",
    skill_automation: "Automatización",
    skill_automation_desc: "Diseño e implementación de pipelines CI/CD para la automatización de despliegues, garantizando la optimización continua de procesos y la calidad del código.",
    skill_agile: "Gestión Ágil",
    skill_agile_desc: "Aplicación de marcos de trabajo ágiles (Scrum y Kanban) para el desarrollo iterativo, maximizando la eficiencia del equipo y asegurando la entrega continua de valor.",
    skill_ia: "Inteligencia Artificial",
    skill_ia_desc: "Desarrollo de modelos predictivos mediante ensambles de gradient boosting y optimización de pesos vectoriales para análisis de datos.",
    skill_tools: "Herramientas",
    skill_tools_desc: "Dominio de control de versiones con Git, administración de entornos operativos en Linux y uso estratégico de asistentes de IA para potenciar la productividad.",
    activities_title: "Actividades",
    act_ieee: "Project Manager · IEEE Computer Society",
    act_ieee_desc: "Coordinación de equipos y gestión de proyectos tecnológicos del capítulo estudiantil.",
    act_chess: "Selección de Ajedrez · ITM",
    act_chess_desc: "Campeón Regional por Equipos (4.º Tablero) — LXVIII Evento Prenacional Deportivo del TecNM",
    act_cia: "Capítulo de Inteligencia Artificial · ITM",
    act_cia_desc: "Participación activa en actividades académicas de IA.",
    langs_title: "Idiomas",
    lang_es: "Español — nativo",
    lang_en: "Inglés — A1 técnico",
    contact_title: "Contacto",
    links_title: "Perfiles",
    link_credly_sub: "Certificaciones",
    link_ms_sub: "Perfil de aprendizaje",
    lang_button: "EN"
  },
  en: {
    title: "Alan Hiram | Portfolio",
    name: "Alan Hiram Álvarez Bazán",
    role: "Developer",
    nav_about: "About",
    nav_skills: "Skills",
    nav_contact: "Contact",
    hero_label: "CV",
    hero_subtitle: "6th semester CSE · ITM — Project Manager IEEE CS",
    about_title: "About me",
    about_bio: "CSE student passionate about software development, automation, and artificial intelligence. As Project Manager at IEEE CS, I lead technical teams and manage innovative projects. Additionally, I am an active member of the ITM Chess Team, which strengthens my logical thinking and strategic analysis.",
    skills_title: "Competencies",
    skill_leadership: "Leadership",
    skill_leadership_desc: "Technical team management, teamwork, and strong communication. Project coordination as PM at IEEE CS.",
    skill_software: "Software Development",
    skill_software_desc: "Architecture and development of web and desktop applications, integrating virtualized environments and Linux labs using Docker containers.",
    skill_automation: "Automation",
    skill_automation_desc: "Design and implementation of CI/CD pipelines for deployment automation, ensuring continuous process optimization and code quality.",
    skill_agile: "Agile Management",
    skill_agile_desc: "Application of agile frameworks (Scrum and Kanban) for iterative development, maximizing team efficiency and ensuring continuous value delivery.",
    skill_ia: "Artificial Intelligence",
    skill_ia_desc: "Development of predictive models through gradient boosting ensembles and vector weight optimization for data analysis.",
    skill_tools: "Tools",
    skill_tools_desc: "Proficiency in version control with Git, administration of Linux operating environments, and strategic use of AI assistants to boost productivity.",
    activities_title: "Activities",
    act_ieee: "Project Manager · IEEE Computer Society",
    act_ieee_desc: "Team coordination and tech project management for the student chapter.",
    act_chess: "Chess Team · ITM",
    act_chess_desc: "Team Regional Champion (4th Board) — 68th TecNM Pre-National Sports Event",
    act_cia: "Artificial Intelligence Chapter · ITM",
    act_cia_desc: "Active participation in AI academic activities.",
    langs_title: "Languages",
    lang_es: "Spanish — native",
    lang_en: "English — A1 technical",
    contact_title: "Contact",
    links_title: "Profiles",
    link_credly_sub: "Certifications",
    link_ms_sub: "Learning profile",
    lang_button: "ES"
  }
};
